common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/IMU_data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    blind: 0.1

mapping:
    acc_cov: 0.5
    gyr_cov: 0.5
    b_acc_cov: 0.01
    b_gyr_cov: 0.01
    fov_degree:    180
    det_range:     66
    extrinsic_est_en:  false     # true: enable the online estimation of IMU-LiDAR extrinsic
    # extrinsic_T: [ -0.004522, -0.272916 , 0.261900]
    # extrinsic_R: [ 0.001581, -0.999940,  0.010861,  
    #                -0.999729, -0.001328 , 0.023251, 
    #                -0.023235, -0.010895 ,-0.999671]
    # extrinsic_R: [  0.0007963, -0.9999997,  0.0000000,
    #                 0.9999997,  0.0007963,  0.0000000,
    #                 0.0000000,  0.0000000,  1.0000000 ]
    extrinsic_T: [0, 0, 0] # [0.31686, 0, 0.26705]

    extrinsic_R: [1, 0, 0,
                 0, 1, 0,
                 0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
